creation_rules:
  - path_regex: \.auto\.tfvars\.enc\.yaml$
  - azure_keyvault: "https://tf-state-aks-otel-kv.vault.azure.net/keys/sopsKey/43ab463b333242f48c726c2b1f760dde"       # replace with your Key Vault key
